version: '3'

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    # image: gustavonovaes/rinha-backend-2024-go:latest
    environment:
      API_PORT: 3000
      DATABASE_URL: "postgres://rinha:rinha@postgres:5432/rinha?sslmode=disable"
    restart: unless-stopped
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50MB

  api02: 
    <<: *api

  nginx:
    image: docker.io/nginx:1.25
    volumes:
      - ./conf/nginx:/etc/nginx/
    depends_on:
      - api01
      - api02
    ports:
      - 9999:80
    restart: unless-stopped
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50MB

  postgres:
    image: docker.io/postgres:16
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./conf/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./conf/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "rinha"
      POSTGRES_USER: "rinha"
      POSTGRES_PASSWORD: "rinha"
    restart: unless-stopped
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 400MB

networks:
  default:
    driver: bridge
    name: network
