version: '3'

services:
  api:
    image: docker.io/golang:1.22
    volumes:
      - .:/app
      - .go/cache:/go/cache
    working_dir: /app
    depends_on:
      - postgres
    environment:
      GOCACHE: /go/cache
      API_PORT: 3000
      DATABASE_URL: "postgres://rinha:rinha@postgres:5432/rinha?sslmode=disable"
    ports: 
      - 9999:3000
    command: "go run ."

  postgres:
    image: docker.io/postgres:16
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./conf/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./conf/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "rinha"
      POSTGRES_USER: "rinha"
      POSTGRES_PASSWORD: "rinha"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 400MB